(function(container, $){
	container.AlertWin = {
		
		showBillList : function(aParam){
			var html = '';
			
			html += '<div class="J-bill-list-win">';
				html += '<div class="content-body">';
					html += '<div class="item-wrap">';
					
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						html += '<div class="c-b-list-item">';
							html += '<div class="c-b-l-i-title">2017-02-03</div>';
							html += '<div class="c-b-l-i-bottom">';
								html += '<a class="l-text"><span>核对数字</span><span>99</span></a>';
								html += '<a class="l-edit"></a>';
								html += '<a class="l-status"></a>';
							html += '</div>';
						html += '</div>';
						
					html += '</div>';
				html += '</div>';
				html += '<div class="content-bottom">';
					html += '<div class="l-btn"></div>';
					html += '<div class="c-txt">1/10</div>';
					html += '<div class="r-btn"></div>';
				html += '</div>';
			html += '</div>';
			
			var oHtml = $(html);
			showAlertWin(oHtml, function(){
				
			});
		}
				
	}
})(window, jQuery);